openapi: 3.0.0
tags:
  - name: ReportGen
get:
  
  description: Generation of client reports
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error